//Do want you want with this trash code :)
package me.captain.adv.dialogue;

/**
 *
 * @author andre
 */
public enum FlagType {
    NONE, QUEST, MAIN_QUEST_COMPLETE, DRAGON_RISING_COMPLETE, NIGHT, THANE, LATE_NIGHT, MORTHAL_BURNED_HOUSE, BEFORE_BLEAK_FALLS, WEAPON_DRAWN,
    FIST_UP, FIST_UP_KHAJIT, CAST_MAGIC, SHOUTED, IGNORE_CRIME, WEREWOLF_HUMAN, VAMPIRE_NO_DAWNGUARD, BOUNTY, ARGONIAN, GUARD_NORD,
    GUARD_NOT_NORD, ELF, KHAJIIT, REDGUARD, IMPERIAL_GUARD_NOT, ORC, IRON_SWORD, STEEL_SWORD, ELVEN_SWORD, EBONY_SWORD, GREATSWORD,
    HIDE_ARMOR, STUDDED_ARMOR, LEATHER_ARMOR, SCALED_ARMOR, IRON_ARMOR, BANDED_IRON_ARMOR, STEEL_ARMOR, DWARVEN_ARMOR, STEEL_PLATE_ARMOR,
    ORCISH_ARMOR, EBONY_ARMOR, DRAGON_PLATE_ARMOR, DRAGON_SCALE_ARMOR, IMPERIAL_ARMOR_GUARD_NOT, IMPERIAL_ARMOR_GUARD_IS,
    IMPERIAL_S_ARMOR_GUARD_NOT, IMPERIAL_S_ARMOR_GUARD_IS, EMPEROR_ALIVE_IMPERIAL, EMPEROR_DEAD_IMPERIAL, STORMCLOAK_ARMOR_G_IS,
    STORMCLOAK_ARMOR_G_NOT, STORMCLOAK_ARMOR_O_IS, STORMCLOAK_ARMOR_O_NOT, ANCIENT_NORD_ARMOR, WOLF_ARMOR, AZURAS_STAR, AEGISBANE,
    MACE_MOLAG, MEHRUNES_RAZOR, NIGHTINGALE_ARMOR, RING_NAMIRA, RUEFUL_AXE, SKULL_CORRUPTION, SPELLBREAKER, THIEVES_GUILD_ARMOR,
    VOLENDRUNG, RIFTEN, SHOP_START, SHOP_END, SHOP_ACCEPT, SHOP_DENY;
}
