//Do want you want with this trash code :)
package me.captain.adv.faction;

/**
 *
 * @author andre
 */
public enum FactionType {
    NONE, STORMCLOAK, IMPERIAL, DARK_BROTHERHOOD, VAMPIRE, BARDS, BLACK_BRIARS, BLADES, 
    NIGHTINGALES, PENITUS_OCULATUS, MYTHIC_DAWN, PSIJIC_ORDER, BATTLE_BORN, BLACK_HAND,
    CULT_MOTH, SHATTER_SHIELD, BLACKBLOOD, NAMIRA, DARKLIGHT, EAST_EMPIRE, FORSWORN,
    DAWNGUARD, SHADOWSCALE, SILVER_HAND, SILVER_BLOODS, SNOW_SHOD, SUMMERSET, SNYOD, 
    THALMOR, CIRCLE, COMPANIONS, GREYBEARDS, THIEVES_GUILD, ORCS, SETNDARR, VOLKIHAR,
    RIFTEN_GUARD;
}
